FROM ansibleplaybookbundle/apb-base:canary

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGhlbGxvLXdvcmxkLWFwYgpkZXNjcmlwdGlvbjogZGVwbG95cyBo\
ZWxsby13b3JsZCB3ZWIgYXBwbGljYXRpb24KYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25h\
bAptZXRhZGF0YToKICBkaXNwbGF5TmFtZTogSGVsbG8gV29ybGQgKEFQQikKICBsb25nRGVzY3Jp\
cHRpb246IEEgc2FtcGxlIEFQQiB3aGljaCBkZXBsb3lzIGEgY29udGFpbmVyaXplZCBIZWxsbyBX\
b3JsZCB3ZWIgYXBwbGljYXRpb24KICBkZXBlbmRlbmNpZXM6IFsnZG9ja2VyLmlvL2Fuc2libGVw\
bGF5Ym9va2J1bmRsZS9oZWxsby13b3JsZDpsYXRlc3QnXQogIHByb3ZpZGVyRGlzcGxheU5hbWU6\
ICJSZWQgSGF0LCBJbmMuIgpwbGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9u\
OiBBIHNhbXBsZSBBUEIgd2hpY2ggZGVwbG95cyBIZWxsbyBXb3JsZAogICAgZnJlZTogVHJ1ZQog\
ICAgbWV0YWRhdGE6CiAgICAgIGRpc3BsYXlOYW1lOiBEZWZhdWx0CiAgICAgIGxvbmdEZXNjcmlw\
dGlvbjogVGhpcyBwbGFuIGRlcGxveXMgYSBQeXRob24gd2ViIGFwcGxpY2F0aW9uIGRpc3BsYXlp\
bmcgSGVsbG8gV29ybGQKICAgICAgY29zdDogJDAuMDAKICAgIHBhcmFtZXRlcnM6IFtdCg=="

ADD playbooks /opt/apb/actions
ADD roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}

USER apb
