# FROM ansibleplaybookbundle/apb-base:canary
FROM docker.io/djzager/apb-base:canary

LABEL "com.redhat.apb.spec"=\
"LS0tCnZlcnNpb246IDEuMApuYW1lOiBoZWxsby13b3JsZC1hcGIKZGVzY3JpcHRpb246IGRlcGxv\
eXMgaGVsbG8td29ybGQgd2ViIGFwcGxpY2F0aW9uCmJpbmRhYmxlOiAiRmFsc2UiCmFzeW5jOiBv\
cHRpb25hbAptZXRhZGF0YToKICBkaXNwbGF5TmFtZTogRFogSGVsbG8gV29ybGQgKEFQQikKICBs\
b25nRGVzY3JpcHRpb246CiAgICBBIHNhbXBsZSBBUEIgd2hpY2ggZGVwbG95cyBhIGNvbnRhaW5l\
cml6ZWQgSGVsbG8gV29ybGQgd2ViIGFwcGxpY2F0aW9uCiAgZGVwZW5kZW5jaWVzOiBbJ2RvY2tl\
ci5pby9hbnNpYmxlcGxheWJvb2tidW5kbGUvaGVsbG8td29ybGQ6bGF0ZXN0J10KICBwcm92aWRl\
ckRpc3BsYXlOYW1lOiAiUmVkIEhhdCwgSW5jLiIKcGxhbnM6CiAgLSBuYW1lOiBkZWZhdWx0CiAg\
ICBkZXNjcmlwdGlvbjogQSBzYW1wbGUgQVBCIHdoaWNoIGRlcGxveXMgSGVsbG8gV29ybGQKICAg\
IGZyZWU6ICJUcnVlIgogICAgbWV0YWRhdGE6CiAgICAgIGRpc3BsYXlOYW1lOiBEZWZhdWx0CiAg\
ICAgIGxvbmdEZXNjcmlwdGlvbjoKICAgICAgICBUaGlzIHBsYW4gZGVwbG95cyBhIFB5dGhvbiB3\
ZWIgYXBwbGljYXRpb24gZGlzcGxheWluZyBIZWxsbyBXb3JsZAogICAgICBjb3N0OiAkMC4wMAog\
ICAgcGFyYW1ldGVyczogW10K"

ADD playbooks /opt/apb/actions

# Add our role into the ansible roles dir
ADD . /opt/ansible/roles/hello-world-apb

RUN chmod -R g=u /opt/{ansible,apb}

USER apb
