FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGhlbGxvLXdvcmxkLWFwYgppbWFnZTogYW5zaWJsZXBsYXlib29r\
YnVuZGxlL2hlbGxvLXdvcmxkLWFwYgpkZXNjcmlwdGlvbjogZGVwbG95cyBoZWxsby13b3JsZCB3\
ZWIgYXBwbGljYXRpb24KYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbAptZXRhZGF0YToK\
ICBkaXNwbGF5TmFtZTogSGVsbG8gV29ybGQgKEFQQikKICBsb25nRGVzY3JpcHRpb246IEEgc2Ft\
cGxlIEFQQiB3aGljaCBkZXBsb3lzIGEgY29udGFpbmVyaXplZCBIZWxsbyBXb3JsZCB3ZWIgYXBw\
bGljYXRpb24KICBkZXBlbmRlbmNpZXM6IFsnZG9ja2VyLmlvL2Fuc2libGVwbGF5Ym9va2J1bmRs\
ZS9oZWxsby13b3JsZDpsYXRlc3QnXQogIHByb3ZpZGVyRGlzcGxheU5hbWU6ICJSZWQgSGF0LCBJ\
bmMuIgpwbGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBBIHNhbXBsZSBB\
UEIgd2hpY2ggZGVwbG95cyBIZWxsbyBXb3JsZAogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6\
CiAgICAgIGRpc3BsYXlOYW1lOiBEZWZhdWx0CiAgICAgIGxvbmdEZXNjcmlwdGlvbjogVGhpcyBw\
bGFuIGRlcGxveXMgYSBQeXRob24gd2ViIGFwcGxpY2F0aW9uIGRpc3BsYXlpbmcgSGVsbG8gV29y\
bGQKICAgICAgY29zdDogJDAuMDAKICAgIHBhcmFtZXRlcnM6IFtdCg=="

ADD playbooks /opt/apb/actions
ADD roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}

USER apb
