---

- name: "Verify {{ app_name }} objects removed"
  command: "oc get {{ item }} -n {{ namespace }} {{ app_name }}"
  register: object
  retries: 10
  delay: 5
  until: object.rc != 0
  failed_when: object.rc == 0
  with_items:
    - DeploymentConfig
    - Service
    - Route
