---

- name: "Verify {{ app_name }} objects exist"
  command: "oc get {{ item }} -n {{ namespace }} {{ app_name }}"
  register: object
  retries: 10
  delay: 5
  until: object.rc == 0
  failed_when: object.rc != 0
  with_items:
    - DeploymentConfig
    - Service
    - Route

- name: Get route
  set_fact:
    route: "{{ lookup('openshift', kind='Route', namespace=namespace, resource_name=app_name) }}"

- name: "Verify route is accessible"
  uri:
    url: "http://{{ route.spec.host }}"
    return_content: yes
  retries: 10
  delay: 5
  register: webpage
  until: webpage.status == 200
