---
apiVersion: v1 # Notice that the prefix was removed from apps.openshift.io/v1
kind: Deployment
metadata:
  labels:
    app: {{ app_name }}
    service: {{ app_name }}
    apb_plan_id: '{{ _apb_plan_id }}'
    apb_service_class_id: '{{ _apb_service_class_id }}'
    apb_service_instance_id: '{{ _apb_service_instance_id }}'
  name: {{ app_name }}
  namespace: {{ namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ app_name }}
      service: {{ app_name }}
  template:
    metadata:
      labels:
        app: {{ app_name }}
        service: {{ app_name }}
    spec:
      containers:
      - image: {{ app_image }}
        name: {{ app }}
        ports:
        - containerPort: 8080
          protocol: TCP
