---
apiVersion: v1 # Notice that the prefix was removed from apps.openshift.io/v1
kind: Deployment
metadata:
  labels:
    apb_name: '{{ apb_name }}'
    apb_plan_id: '{{ _apb_plan_id }}'
    apb_service_class_id: '{{ _apb_service_class_id }}'
    apb_service_instance_id: '{{ _apb_service_instance_id }}'
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ name }}
      service: {{ name }}
  template:
    metadata:
      labels:
        app: {{ name }}
        service: {{ name }}
    spec:
      containers:
      - image: {{ image }}
        name: {{ apb_name }}
        ports:
        - containerPort: 8080
          protocol: TCP
