---
apiVersion: v1 # Notice that the prefix was removed from route.openshift.io/v1
kind: Route
metadata:
  labels:
    apb_name: '{{ apb_name }}'
    apb_plan_id: '{{ _apb_plan_id }}'
    apb_service_class_id: '{{ _apb_service_class_id }}'
    apb_service_instance_id: '{{ _apb_service_instance_id }}'
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  port:
    targetPort: web
  to:
    kind: Service
    name: {{ name }}
