- name: hello-world-apb deprovision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansibleplaybookbundle.asb-modules
  - role: hello-world-apb
  vars:
    apb_action: deprovision
