- name: hello-world-apb provision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansibleplaybookbundle.asb-modules
  tasks:
    - name: Provision test
      include_role:
        name: hello-world-apb
      vars:
        apb_action: provision
        in_cluster: False

    - name: Deprovision test
      include_role:
        name: hello-world-apb
      vars:
        apb_action: deprovision
        in_cluster: False
