- name: hello-world-apb provision
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Provision test
      include_role:
        name: apb
      vars:
        apb_action: provision

    - name: Deprovision test
      include_role:
        name: apb
      vars:
        apb_action: deprovision
